# Generated by Django 3.1.4 on 2023-04-05 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PredResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery', models.IntegerField(null=True)),
                ('rpm', models.IntegerField(null=True)),
                ('headlight', models.IntegerField(null=True)),
                ('buzzer', models.IntegerField(null=True)),
                ('led', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Omo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery', models.IntegerField(default=0, null=True)),
                ('bat_status', models.CharField(default='on', max_length=10, null=True)),
                ('r_led', models.IntegerField(default=0, null=True)),
                ('g_led', models.IntegerField(default=0, null=True)),
                ('b_led', models.IntegerField(default=0, null=True)),
                ('r_rpm', models.IntegerField(default=0, null=True)),
                ('l_rpm', models.IntegerField(default=0, null=True)),
                ('buzzer', models.CharField(default='off', max_length=10, null=True)),
                ('headlight', models.CharField(default='off', max_length=10, null=True)),
                ('content', models.TextField(default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default='', max_length=30, null=True)),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
